ARG BASE_TAG="ghcr.io/depau/wine-docker-base:latest"
ARG BASE_PLATFORM=linux/amd64
ARG UBUNTU_VERSION=questing

###############################################
FROM --platform=$BASE_PLATFORM $BASE_TAG AS fex_rootfs

###############################################
FROM ubuntu:$UBUNTU_VERSION
LABEL org.opencontainers.image.authors="Davide Depau <davide@depau.eu>"

RUN if getent passwd 1000 >/dev/null 2>&1; then \
      userdel --remove "$(id -nu 1000)"; \
    fi && \
    useradd -m -d /home/wineuser -s /bin/bash --uid 1000 wineuser && \
    mkdir /tmp/.X11-unix && \
    chmod 1777 /tmp/.X11-unix && \
    # Make sure subsequent Dockerfile RUN statement uses bash \
    mv /bin/sh /bin/sh.old && \
    ln -s /bin/bash /bin/sh

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bash \
        ca-certificates \
        locales \
        software-properties-common \
        tini \
        wget \
        x11-utils  \
        xvfb \
      && \
    locale-gen en_US.UTF-8 && \
    add-apt-repository -y ppa:fex-emu/fex && \
    apt-get install -y --no-install-recommends fex-emu-armv8.0 && \
    rm -rf /var/lib/apt/lists/*

ENV WINEDEBUG=-all,-fixme,-fixme-all \
    XVFB_SCREEN=0 \
    XVFB_RESOLUTION="320x240x8" \
    DISPLAY=":95" \
    LANG=en_US.UTF-8

# Use the x86_64 base build of this image as the FEX rootfs
COPY --from=fex_rootfs \
    --chown=wineuser:wineuser \
    --exclude=hosts \
    --exclude=resolv.conf \
    --exclude=timezone \
    --exclude=localtime \
    --exclude=passwd \
    /etc /home/wineuser/.fex-emu/RootFS/amd64/etc/

COPY --from=fex_rootfs \
    --chown=wineuser:wineuser \
    --exclude=cache/apt/* \
    --exclude=lib/apt/* \
    /var /home/wineuser/.fex-emu/RootFS/amd64/var/

COPY --from=fex_rootfs \
    --chown=wineuser:wineuser \
    /bin /home/wineuser/.fex-emu/RootFS/amd64/bin/

COPY --from=fex_rootfs \
    --chown=wineuser:wineuser \
    /sbin /home/wineuser/.fex-emu/RootFS/amd64/sbin/

COPY --from=fex_rootfs \
    --chown=wineuser:wineuser \
    /lib /home/wineuser/.fex-emu/RootFS/amd64/lib/

COPY --from=fex_rootfs \
    --chown=wineuser:wineuser \
    /lib64 /home/wineuser/.fex-emu/RootFS/amd64/lib64/

COPY --from=fex_rootfs \
    --chown=wineuser:wineuser \
    /opt /home/wineuser/.fex-emu/RootFS/amd64/opt/

COPY --from=fex_rootfs \
    --chown=wineuser:wineuser \
    /usr /home/wineuser/.fex-emu/RootFS/amd64/usr/


USER wineuser
RUN echo '{"Config":{"RootFS":"amd64"}}' > /home/wineuser/.fex-emu/Config.json && \
    FEXBash -c 'wine --version'  # Try it out

USER root
RUN while read -r winebin; do \
      basename="$(basename "$winebin")"; \
      echo -e '#!/usr/bin/FEXInterpreter /home/wineuser/.fex-emu/RootFS/amd64/bin/bash\nexec /opt/wine-stable/bin/'"$basename"' "$@"' > "/usr/local/bin/$basename"; \
      chmod +x "/usr/local/bin/$basename"; \
    done < <(find /home/wineuser/.fex-emu/RootFS/amd64/opt/wine-stable/bin -mindepth 1) && \
    mkdir -pm755 /opt && \
    ln -s /home/wineuser/.fex-emu/RootFS/amd64/opt/wine-stable /opt/wine-stable

COPY scripts/download_gecko_and_mono.sh /usr/local/bin/download_gecko_and_mono.sh

RUN WINE_VERSION="$(su wineuser -c 'wine --version' | sed -E 's/^wine-([0-9]*.[0-9]*).*/\1/')"; \
    chmod +x /usr/local/bin/download_gecko_and_mono.sh && \
    download_gecko_and_mono.sh "$WINE_VERSION"

COPY scripts/auto_xvfb.sh /usr/local/bin/auto_xvfb

USER wineuser

RUN source auto_xvfb && \
    wineboot -i && \
    wineserver -k
