ARG BUILDPLATFORM
ARG UBUNTU_VERSION=questing

###############################################
FROM --platform=$BUILDPLATFORM ubuntu:$UBUNTU_VERSION AS downloader

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget \
        ca-certificates \
        gnupg

RUN . /etc/os-release && \
    mkdir /dl && \
    wget -O - https://dl.winehq.org/wine-builds/winehq.key | gpg --dearmor -o /dl/winehq-archive.key && \
    wget -O /dl/winehq.sources https://dl.winehq.org/wine-builds/$ID/dists/$VERSION_CODENAME/winehq-$VERSION_CODENAME.sources && \
    wget -O /dl/winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

###############################################
FROM ubuntu:$UBUNTU_VERSION
LABEL org.opencontainers.image.authors="Davide Depau <davide@depau.eu>"

RUN if getent passwd 1000 >/dev/null 2>&1; then \
      userdel --remove "$(id -nu 1000)"; \
    fi && \
    useradd -m -d /home/wineuser -s /bin/bash --uid 1000 wineuser && \
    mkdir /tmp/.X11-unix && \
    chmod 1777 /tmp/.X11-unix && \
    # Make sure subsequent Dockerfile RUN statement uses bash \
    mv /bin/sh /bin/sh.old && \
    ln -s /bin/bash /bin/sh

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bash \
        ca-certificates \
        gosu \
        locales \
        wget \
      && \
    locale-gen en_US.UTF-8 && \
    rm -rf /var/lib/apt/lists/*

RUN --mount=type=bind,from=downloader,source=/dl,target=/mnt \
    set -x && \
    mkdir -pm755 /etc/apt/keyrings && \
    cp /mnt/winehq-archive.key /etc/apt/keyrings/ && \
    cp /mnt/winehq.sources /etc/apt/sources.list.d/ && \
    dpkg --add-architecture i386 &&  \
    apt-get update && \
    apt-get install -y --no-install-recommends winehq-stable && \
    rm -rf /var/lib/apt/lists/* && \
    rm -f /tmp/.X*lock

ENV WINEDEBUG=-all,-fixme,-fixme-all \
    XVFB_SCREEN=0 \
    XVFB_RESOLUTION="320x240x8" \
    DISPLAY=":95" \
    LANG=en_US.UTF-8

COPY --from=downloader --chmod=0755 /dl/winetricks /usr/bin/winetricks
