ARG BASE_TAG="ghcr.io/depau/wine-docker-base:latest"

###############################################
FROM $BASE_TAG
LABEL org.opencontainers.image.authors="Davide Depau <davide@depau.eu>"

USER root

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        tini \
        x11-utils  \
        xvfb \
      && \
    rm -rf /var/lib/apt/lists/*

COPY scripts/download_gecko_and_mono.sh /usr/local/bin/download_gecko_and_mono.sh

RUN chmod +x /usr/local/bin/download_gecko_and_mono.sh && \
    download_gecko_and_mono.sh "$(wine --version | sed -E 's/^wine-([0-9]*.[0-9]*).*/\1/')"

COPY scripts/auto_xvfb.sh /usr/local/bin/auto_xvfb

USER wineuser

RUN source auto_xvfb && \
    wineboot -i && \
    wineserver -k
